model_inputs:
  lstm:
  - text_raw_indices
  td_lstm: 
  - text_left_with_aspect_indices
  - text_right_with_aspect_indices
  ian: 
  - text_raw_indices
  - aspect_indices
  ram: 
  - text_raw_indices
  - aspect_indices
  - text_left_indices
  tnet_lf: 
  - text_raw_indices
  - aspect_indices
  - aspect_in_text
  aen_bert: 
  - text_raw_bert_indices
  - aspect_bert_indices
  lcf_bert: 
  - text_bert_indices
  - bert_segments_ids
  - text_raw_bert_indices
  - aspect_bert_indices
  mgan:
  - text_raw_indices
  - aspect_indices
  - text_left_indices
  cabasc:
  - text_raw_indices
  - aspect_indices
  - text_left_with_aspect_indices
  - text_right_with_aspect_indices

datasets:
  coref_twitter:
    train: ./datasets/coref_existing/augmented_twitter_train.litesent
    test: ./datasets/acl-14-short-data/test.raw
  coref_restaurant:
    train: ./datasets/coref_existing/augmented_restaurants_train.litesent
    test: ./datasets/semeval14/Restaurants_Test_Gold.xml.seg
  coref_laptop:
    train: ./datasets/coref_existing/augmented_laptops_train.litesent
    test: ./datasets/semeval14/Laptops_Test_Gold.xml.seg
  twitter:
    train: ./datasets/acl-14-short-data/train.raw
    test: ./datasets/acl-14-short-data/test.raw
  restaurant:
    train: ./datasets/semeval14/Restaurants_Train.xml.seg
    test: ./datasets/semeval14/Restaurants_Test_Gold.xml.seg
  laptop:
    train: ./datasets/semeval14/Laptops_Train.xml.seg
    test: ./datasets/semeval14/Laptops_Test_Gold.xml.seg
  laptop_business:
    train: ./datasets/topics/business_distant.litesent
    test: ./datasets/semeval14/Laptops_Test_Gold.xml.seg
  laptop_politics:
    train: ./datasets/topics/politics_distant.litesent
    test: ./datasets/semeval14/Laptops_Test_Gold.xml.seg
  laptop_sports:
    train: ./datasets/topics/sports_distant.litesent
    test: ./datasets/semeval14/Laptops_Test_Gold.xml.seg
  laptop_tech:
    train: ./datasets/topics/tech_distant.litesent
    test: ./datasets/semeval14/Laptops_Test_Gold.xml.seg
  ood_twitter:
    train: ./datasets/all_entities.litesent
    test: ./datasets/acl-14-short-data/test.raw
  ood_twitter_train:
    train: ./datasets/all_entities.litesent
    test: ./datasets/acl-14-short-data/train.raw
  ood_restaurant:
    train: ./datasets/all_entities.litesent
    test: ./datasets/semeval14/Restaurants_Test_Gold.xml.seg
  ood_restaurant_train:
    train: ./datasets/all_entities.litesent
    test: ./datasets/semeval14/Restaurants_Train.xml.seg
  ood_laptop:
    train: ./datasets/all_entities.litesent
    test: ./datasets/semeval14/Laptops_Test_Gold.xml.seg
  ood_laptop_train:
    train: ./datasets/all_entities.litesent
    test: ./datasets/semeval14/Laptops_Train.xml.seg
  distant_no_leakage:
    train: ./datasets/all_entities.litesent
    test: ./datasets/entities_no_leakage_test.litesent
  coref_distant_no_leakage:
    train: ./datasets/coref_strise_data/coref_no_leakage_train_fixed.litesent
    test: ./datasets/entities_no_leakage_test.litesent
  coref_both_no_leakage:
    train: ./datasets/coref_strise_data/coref_no_leakage_train.litesent
    test: ./datasets/coref_strise_data/coref_no_leakage_test.litesent
  distant_gold_eval_59:
    train: ./datasets/all_entities.litesent
    test: ./datasets/sampled_59_docs.litesent
  coref_gold_eval_59:
    train: ./datasets/coref_all_entities.litesent
    test: ./datasets/sampled_59_docs.litesent
  coref_gold_coref_eval_59:
    train: ./datasets/coref_all_entities.litesent
    test: ./datasets/coref_59_docs.litesent
  COREF_TEST_59: 
    train: ./datasets/all_entities.litesent
    test: ./datasets/coref_59_docs.litesent
  distant:
    train: ./datasets/entities_distant_train.litesent
    test: ./datasets/entities_distant_test.litesent
  distant_time:
    train: ./datasets/time_data/2018-2019.litesent
    test: ./datasets/time_data/2020.litesent
  coref_time:
    train: ./datasets/time_data/coref-2018-2019.litesent
    test: ./datasets/time_data/2020.litesent
  coref_time_both:
    train: ./datasets/time_data/coref-2018-2019.litesent
    test: ./datasets/time_data/coref-2020.litesent
  TESTCOREF_laptop:
    train: ./datasets/semeval14/Laptops_Train.xml.seg
    test: ./datasets/coref_existing/augmented_laptops_test_gold.litesent
  TESTCOREF_rest:
    train: ./datasets/semeval14/Restaurants_Train.xml.seg
    test: ./datasets/coref_existing/augmented_restaurants_test_gold.litesent
  RESTAURANT_GOLD_COREF: 
    train: ./datasets/semeval14/Restaurants_Train.xml.seg
    test: ./datasets/coref_59_docs.litesent
  LAPTOP_GOLD_COREF: 
    train: ./datasets/semeval14/Laptops_Train.xml.seg
    test: ./datasets/coref_59_docs.litesent
